### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by vodik** [SIPp/pysipp#14]
Tried to run it on python35, got

```
Traceback (most recent call last):
  File "/root/.virtualenv/pylab3/lib/python3.5/site-packages/_pytest/config.py", line 385, in import_plugin
    __import__(importspec)
  File "/root/mirror/sangoma/sipp/__init__.py", line 1, in <module>
    from sangoma.sipp.plugin import *
  File "/root/mirror/sangoma/sipp/plugin.py", line 11, in <module>
    import pysipp
  File "/root/.virtualenv/pylab3/src/pysipp/pysipp/__init__.py", line 23, in <module>
    from load import iter_scen_dirs
ImportError: No module named 'load'
```

**Comment by goodboy** [comment]
Pretty sure this was fixed by the above commit.
