### ISSUE TITLE
ValueError: xml script must contain one of 'uac' or 'uas':

### ISSUE THREAD

**Issue by access2praveen** [SIPp/pysipp#39]
I am getting below error if i am trying to execute all my sipp xml files in a directory 
`Traceback (most recent call last):
  File "sipp.py", line 5, in <module>
    scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR',proxyaddr=('10.204.66.84', 5080))
  File "/usr/local/lib/python3.5/dist-packages/pysipp/__init__.py", line 98, in scenario
    **scenkwargs)
  File "/usr/local/lib/python3.5/dist-packages/pysipp/__init__.py", line 72, in walk
    .format(xml)
ValueError: xml script must contain one of 'uac' or 'uas':
/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR/AMR_oct_modeset_1.xml
`

My python code look as below 

import pysipp
uas = pysipp.server(srcaddr=('10.204.66.84', 5080))
uac = pysipp.client(destaddr=uas.srcaddr)
scen = pysipp.scenario()
scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR',proxyaddr=('10.204.66.84', 5080))
 

Please help me how to get rid of this problem

**Comment by tgoodlet** [comment]
Hi @access2praveen. This error is saying you must have one of `uac` or `uas` in the file name for each xml script. The error could probably be made more clear. `pysipp` uses the file name to figure out how to launch the underlying script (as a client vs server).

**Comment by access2praveen** [comment]
Thanks, Upon prefixing scenario files with UAC, I got rid of this error , However i am seeing below error 

`stderr for 'uac_AMR' @ ('0.0.0.0', 33879)
b'2018-08-20\t14:10:28.359428\t1534738228.359428: Missing remote host parameter. This scenario requires it.\n'`

My script is written as below

import pysipp
uas = pysipp.server(srcaddr=('10.204.66.84', 5080))
print(uas.srcaddr)
uac = pysipp.client(destaddr=uas.srcaddr)

scen = pysipp.scenario()
scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR',proxyaddr=('10.204.66.84', 5080))
scen()
pysipp.log_to_stderr('DEBUG')

**Comment by tgoodlet** [comment]
Hey @access2praveen sorry about the delay getting back to you.

If you're trying to load a *directory* of `SIPp` xml scripts the `pysipp.scenario()` should work the best as it does a bunch of automatic socket addr configuration for you.

For this code:
```python
scen = pysipp.scenario()
scen = pysipp.scenario(dirpath='/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR',proxyaddr=('10.204.66.84', 5080))
scen()
pysipp.log_to_stderr('DEBUG')
```
Before you call `scen()` can you run `print(scen.cmditems()`? This should give us a clue what might be wrong. Also note, you should put `pysipp.log_to_stderr('DEBUG')` **before** any of your other code to enable logging before calling the `pysipp` api.

**Comment by access2praveen** [comment]
I m seeing below message 

`('10.204.66.84', 5080)
[('uac_AMR', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '41143' -mi '0.0.0.0' -mp '59201' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_log_file' -screen_file '/tmp/uac_AMR_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '33263' -mi '0.0.0.0' -mp '34796' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_log_file' -screen_file '/tmp/uac_AMR_BW_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW_modeset_0', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '45016' -mi '0.0.0.0' -mp '58080' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW_modeset_0.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_modeset_0_log_file' -screen_file '/tmp/uac_AMR_BW_modeset_0_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW_modeset_0to7', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '48093' -mi '0.0.0.0' -mp '36462' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW_modeset_0to7.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_modeset_0to7_log_file' -screen_file '/tmp/uac_AMR_BW_modeset_0to7_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW_modeset_2', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '57536' -mi '0.0.0.0' -mp '52823' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW_modeset_2.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_modeset_2_log_file' -screen_file '/tmp/uac_AMR_BW_modeset_2_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW_modeset_7', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '57469' -mi '0.0.0.0' -mp '39997' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW_modeset_7.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_modeset_7_log_file' -screen_file '/tmp/uac_AMR_BW_modeset_7_screen_file' -trace_logs -trace_screen "), ('uac_AMR_BW_modeset_8', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '49559' -mi '0.0.0.0' -mp '59224' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW_modeset_8.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_BW_modeset_8_log_file' -screen_file '/tmp/uac_AMR_BW_modeset_8_screen_file' -trace_logs -trace_screen "), ('uac_AMR_INTERLEAVING_EN', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '53617' -mi '0.0.0.0' -mp '51044' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_INTERLEAVING_EN.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_INTERLEAVING_EN_log_file' -screen_file '/tmp/uac_AMR_INTERLEAVING_EN_screen_file' -trace_logs -trace_screen "), ('uac_AMR_Invalid_Max-Red', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '41776' -mi '0.0.0.0' -mp '58968' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_Invalid_Max-Red.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_Invalid_Max-Red_log_file' -screen_file '/tmp/uac_AMR_Invalid_Max-Red_screen_file' -trace_logs -trace_screen "), ('uac_AMR_Negative_Max-Red', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '44934' -mi '0.0.0.0' -mp '46192' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_Negative_Max-Red.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_Negative_Max-Red_log_file' -screen_file '/tmp/uac_AMR_Negative_Max-Red_screen_file' -trace_logs -trace_screen "), ('uac_AMR_TE', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '46205' -mi '0.0.0.0' -mp '48974' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_TE.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_TE_log_file' -screen_file '/tmp/uac_AMR_TE_screen_file' -trace_logs -trace_screen "), ('uac_AMR_Valid_Max-Red', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '49971' -mi '0.0.0.0' -mp '54053' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_Valid_Max-Red.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_Valid_Max-Red_log_file' -screen_file '/tmp/uac_AMR_Valid_Max-Red_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '59490' -mi '0.0.0.0' -mp '52385' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_log_file' -screen_file '/tmp/uac_AMR_oct_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_0', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '42814' -mi '0.0.0.0' -mp '38206' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_0.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_0_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_0_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_0to7', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '41827' -mi '0.0.0.0' -mp '49759' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_0to7.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_0to7_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_0to7_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_1', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '38371' -mi '0.0.0.0' -mp '42896' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_1.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_1_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_1_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_2', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '46891' -mi '0.0.0.0' -mp '58354' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_2.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_2_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_2_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_7', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '59434' -mi '0.0.0.0' -mp '46915' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_7.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_7_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_7_screen_file' -trace_logs -trace_screen "), ('uac_AMR_oct_modeset_8', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '41935' -mi '0.0.0.0' -mp '44208' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_oct_modeset_8.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_AMR_oct_modeset_8_log_file' -screen_file '/tmp/uac_AMR_oct_modeset_8_screen_file' -trace_logs -trace_screen "), ('uac_All_Supported_Codecs', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '41889' -mi '0.0.0.0' -mp '43425' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_All_Supported_Codecs.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_All_Supported_Codecs_log_file' -screen_file '/tmp/uac_All_Supported_Codecs_screen_file' -trace_logs -trace_screen "), ('uac_TE_AMR', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '35574' -mi '0.0.0.0' -mp '51037' -sf '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_TE_AMR.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/uac_TE_AMR_log_file' -screen_file '/tmp/uac_TE_AMR_screen_file' -trace_logs -trace_screen ")]
stderr for 'uac_AMR' @ ('0.0.0.0', 41143)
b'2018-08-27\t13:58:07.957001\t1535342287.957001: Missing remote host parameter. This scenario requires it.\n'

'screen_file' contents for 'uac_AMR' @ ('0.0.0.0', 41143):

stderr for 'uac_AMR_BW' @ ('0.0.0.0', 33263)
b'2018-08-27\t13:58:07.963170\t1535342287.963170: Missing remote host parameter. This scenario requires it.\n'

`

**Comment by access2praveen** [comment]
Any idea about this error ?

**Comment by tgoodlet** [comment]
@access2praveen I can't really diagnose without seeing the logging that `pysipp` would normally report.
This just looks like you printing a bunch of `SIPp` commands using some `pysipp.py` script?

I'm not sure what code you used to generate this nor can I see any readable errors.

**Comment by tgoodlet** [comment]
@access2praveen actually this might be the bug #36!
There was an open PR by @y-luis but it seems to have not gotten merged.

**Comment by tgoodlet** [comment]
@access2praveen try out #46. My initial tests seem to fix this.

**Comment by access2praveen** [comment]
Hello tgoodlet
Sorry for the delayed response


The below script worked for me to execute single scenario file 
`import pysipp
uac = pysipp.client(destaddr=('10.204.66.84',5080))
uac.local_host='10.204.66.30'
uac.local_port='5030'
uac.scen_file = '/home/voiceqa/sipp-3.5.1/AMR_Testing/AMR-WB/uac_AMR_BW.xml'
uac()
`

But I want to execute all the scenarios in AMR-WB directory sequentially 

Please help me to tweak my script for the same 

Thanks
Praveen

**Comment by goodboy** [comment]
@access2praveen what is the error you get when trying to exec sequentially?

**Comment by Kallows** [comment]
Hi i got the same issue as described above. If I run the above mention command I receive the following error message.
```
  File "./sipp_test.py", line 11
    uac = pysipp.client(destaddr=('192.168.2.12',5060) uac.local_host=('192.168.2.11',5060) uac.scen_file ='/home/sipp/ai_call_rtp')
                                                          ^
SyntaxError: invalid syntax

```
My py script1 is the following:

```
import pysipp
uac = pysipp.client(destaddr=('192.168.2.12',5060) uac.local_host=('192.168.2.11',5060) uac.scen_file ='/home/sipp/ai_call_rtp')
#uac()
print(scen.cmditems())

```
My main goal would be to change the transport protocol for uas & uac to tcp and change the source and local port ip? Could you please tell me how I can do this. 
I tried also the following without success:

Script2:
```
import pysipp
scen = pysipp.scenario(dirpath='/home/sipp/zzpl/GKCalls/ai_ptime_call_rtp',proxyaddr=('192.168.178.11', 5060))
print(scen.cmditems())
```

Output Script2:
```
[('sipp_uas_gk_ptime_call_rtp', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '38189' -mi '0.0.0.0' -mp '56622' -sf '/home/sipp/zzpl/GKCalls/ai_ptime_call_rtp/sipp_uas_gk_ptime_call_rtp.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/sipp_uas_gk_ptime_call_rtp_log_file' -screen_file '/tmp/sipp_uas_gk_ptime_call_rtp_screen_file' -trace_logs -trace_screen "), ('sipp_uac_gk_ptime_call_rtp', "'/usr/local/bin/sipp' -i '0.0.0.0' -p '51278' -rsa '192.168.2.11':'5060' -mi '0.0.0.0' -mp '35048' -sf '/home/sipp/zzpl/GKCalls/ai_ptime_call_rtp/sipp_uac_gk_ptime_call_rtp.xml' -recv_timeout '5000' -r '1' -l '1' -m '1' -log_file '/tmp/sipp_uac_gk_ptime_call_rtp_log_file' -screen_file '/tmp/sipp_uac_gk_ptime_call_rtp_screen_file' -trace_logs -trace_screen '0.0.0.0':'38189'")]
```
the scen funktion is loading both scenario files correctly but I don't know how I can replace the args values in the cmd command to customize my sipp request.

Would be assume if someone could help me with that. 

Thanks
Kallows

**Comment by divinj** [comment]
@Kallows I was able to do the following to override the defaults.

sipp_options={
'call_count' : 1,
'info_file' : 'scenarios/register.csv',
'transport' : 't1',
'remote_host' : '192.168.1.1',
'remote_port': '5060'
}
scen = pysipp.scenario(dirpath='/home/ec2-user/did-testing/scenarios',defaults=sipp_options,proxyaddr=('192.168.1.1', 5060))
