### ISSUE TITLE
Unable to run with Poetry

### ISSUE THREAD

**Issue by schuettc** [SIPp/pysipp#89]
(sip-load-tester-py3.9)  xxxxxxx/sip-load-tester  python3 sip_load_tester/index.py
Traceback (most recent call last):
  File "/Users/xxxxxxx/Documents/GitHub/xxxxxxx/sip-load-tester/sip_load_tester/index.py", line 1, in <module>
    import pysipp
  File "/Users/xxxxxxx/Library/Caches/pypoetry/virtualenvs/sip-load-tester-hHnEooQS-py3.9/lib/python3.9/site-packages/pysipp/__init__.py", line 24, in <module>
    from . import launch
  File "/Users/xxxxxxx/Library/Caches/pypoetry/virtualenvs/sip-load-tester-hHnEooQS-py3.9/lib/python3.9/site-packages/pysipp/launch.py", line 26, in <module>
    class PopenRunner(object):
  File "/Users/xxxxxxx/Library/Caches/pypoetry/virtualenvs/sip-load-tester-hHnEooQS-py3.9/lib/python3.9/site-packages/pysipp/launch.py", line 38, in PopenRunner
    poller=select.epoll,
AttributeError: module 'select' has no attribute 'epoll'

pyproject.toml:

```
[tool.poetry]
name = "sip-load-tester"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "sip_load_tester"}]

[tool.poetry.dependencies]
python = "^3.9"
pysipp = {git = "https://github.com/SIPp/pysipp.git"}


[tool.poetry.group.dev.dependencies]
pylint = "^2.16.2"
pycodestyle = "^2.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

index.py
```
import pysipp
pysipp.client(destaddr=('10.10.8.88', 5060))()

uas = pysipp.server(srcaddr=('10.10.8.88', 5060))
uac = pysipp.client(destaddr=uas.srcaddr)
# run server async
uas(block=False)  # returns a `pysipp.launch.PopenRunner` instance by default
uac()  # run client synchronously
```

**Comment by goodboy** [comment]
@schuettc looks like a OS stdlib mis-compat:
https://docs.python.org/3/library/select.html#select.epoll

Given ur masked filepaths, looks like you're not on linux.
Also, in this case this is **exactly the motivation to land #87**.

Not sure it has anything to do with "poetry" 😉

**Comment by schuettc** [comment]
This was done on a Mac, not Windows.

**Comment by goodboy** [comment]
@schuettc lol ma bad.

in that case you could try to use the now somewhat defunct https://github.com/SIPp/pysipp/pull/17, but ideally if you can prove #87 works on OS X that would be pretty great 😎
