### ISSUE TITLE
Unable to use pysipp (imp error)

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [SIPp/pysipp#93]
Traceback (most recent call last):
  File "aa.py", line 1, in <module>
    import pysipp
  File "C:\Users\ayu12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pysipp\__init__.py", line 23, in <module>
    from . import launch, report, plugin, netplug, agent
  File "C:\Users\ayu12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pysipp\launch.py", line 11, in <module>
    from . import utils
  File "C:\Users\ayu12\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pysipp\utils.py", line 2, in <module>
    import imp  # XXX py2.7
    ^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'

**Comment by orgads** [comment]
This was fixed in 64df392a05. Please install from git:
```
pip install git+git://github.com/SIPp/pysipp.git
```
